### ISSUE TITLE
CircleCI 2.0 に追従できていない

### ISSUE THREAD

**Issue by uknmr** [uknmr/stylelint-config-mediba#16]
https://circleci.com/gh/mediba-system/stylelint-config/56

- Node v4.2.6 で動いてテストがコケてる
- Yarn が使われていない

docker-image の指定方が変わったのか（あるいは端から間違っていた）と思う。
https://circleci.com/docs/2.0/language-javascript/
https://circleci.com/docs/2.0/circleci-images/#nodejs

**Comment by mediba-Kitada** [comment]
👀

**Comment by uknmr** [comment]
β 外れたしねー

via [2.0 - Continuous Integration Workflows | CircleCI](
https://circleci.com/blog/launching-today-circleci-2-0-reaches-general-availability/?mkt_tok=eyJpIjoiTVRrNE56STJNekV5TkRVMCIsInQiOiJPSG4rRXFvbzBHU1MrMUQxQmZyMVR5OU01TmwrdE9YUlwvRlkzU3ZRQW0rK2Z6ZXREWmZsUjNWakdXSkxvb2FHV1ZXaEVkbmtMTzc1TGtGUnhEYUFtcGZtZXNRcUZJeFpKZkpJTlJFbHZVOXJ0bzBtY1dTR05NM0t5YWZCOEdVN2gifQ%3D%3D)
